# Generated by Django 3.1 on 2020-10-19 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Played')], default=0)),
                ('start_game', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=5)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_scale', to='st.member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_scale', to='st.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='st.party'),
        ),
        migrations.AddField(
            model_name='member',
            name='present_to',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='st.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'party')},
        ),
    ]
